[versions]
#plugins
kotlin = "2.3.0"
agp = "8.13.2"

#libraries
coreKtx = "1.17.0"
appCompat = "1.7.1"
material = "1.13.0"
constraintLayout = "2.2.1"
junit = "4.13.2"
androidTestExtJunit = "1.3.0"
espressoCore = "3.7.0"
androidLogger = "2.1.6"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
junit = { module = "junit:junit", version.ref = "junit" }
androidTestExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidTestExtJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
android-logger = { module = "com.github.toyota-m2k:android-logger", version.ref = "androidLogger" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
